apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        kubernetes.io/cluster-service: true
    spec:
      containers:
      - image: nginx
        name: nginx
        stdin: true
        tty: true
