apiVersion: apps/v1beta2
kind: Deployment
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 1
      containers:
      - image: nginx
        name: nginx
        stdin: true
        tty: true
