apiVersion: apps/v1beta2
kind: Deployment
spec:
  name: nginx
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        stdin: true
        tty: true
