apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: {{ .Values.image }}
        name: nginx
        ports:
          - containerPort: 80
            name: 80tcp01
            protocol: TCP
        stdin: true
        tty: true
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: nginx
        name: nginx
        stdin: true
        tty: true
